# Use the latest PHP image with Apache
FROM mysql:8.0-debian

# Set the desired directories
ENV MYSQL_LOG_DIR /var/log/mysql
ENV MYSQL_DATA_DIR /var/lib/mysql

# Check if the log directory exists, and if not, create it
RUN if [ ! -d "$MYSQL_LOG_DIR" ]; then mkdir -p "$MYSQL_LOG_DIR"; fi

# Set the correct ownership and permissions for the log directory
RUN chown -R mysql:mysql "$MYSQL_LOG_DIR" && chmod 755 "$MYSQL_LOG_DIR"

# Check if the data directory exists, and if not, create it
RUN if [ ! -d "$MYSQL_DATA_DIR" ]; then mkdir -p "$MYSQL_DATA_DIR"; fi

# Set the correct ownership and permissions for the data directory
RUN chown -R mysql:mysql "$MYSQL_DATA_DIR" && chmod 700 "$MYSQL_DATA_DIR"

COPY my.cnf /etc/mysql/conf.d/
RUN chmod 644 /etc/mysql/conf.d/my.cnf

# Copy application files
COPY ./db-scripts /docker-entrypoint-initdb.d/
